name: aplikasi_wisata
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  curved_navigation_bar : ^1.0.3
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.6
  like_button : ^2.0.5
  material_design_icons_flutter: ^7.0.7296
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true

  assets:
    - images/logo_telkom.png
    - images/logo.png
    - images/onboarding1.png
    - images/onboarding2.png
    - images/Baby.png
    - images/news1.png
    - images/news2.jpeg
    - images/news3.jpeg
    - images/nasi.webp
    - images/asi.png
    - images/bubur_instan.png
    - images/bubur.png
    - images/biskuit.png
    - images/cemilan.png


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
 
